### ISSUE TITLE
`height: 100%` op `html, body`

### ISSUE THREAD

**Issue by KrijnHoetmer** [dvens/browser-technologies#4]
``` CSS
body, 
html {
    height: 100%;
    width: 100%;
}
```

Dit is meestal een teken dat er dingen niet helemaal lekker gaan in CSS (aka code smell). Zie zo even snel alleen issues in 'Device mode' in Devtools, met dubbele scrollbare onderdelen, en ik denk dat dat hierdoor komt. In het kort: pas op met `height: 100%` op `html,body`.
